### ISSUE TITLE
Home Assistant loses nodes - New install is 0.59.0 - Upgrade to 0.62.2 not possible!

### ISSUE THREAD

**Issue by Rohrleitner** [zachowj/node-red-contrib-home-assistant-websocket#1238] opened 2024-01-04 16:59 UTC
### Describe the bug

All Nodes get lost in Home Assistant.
After new installation from [node-red-contrib-home-assistant-websocket] only version 0.59.0 is installed.
Upgrade to 0.62.2 is shown but after a manual restart of the node red Addon every nodes are away again!

 Add-on version: 16.0.2
 You are running the latest version of this add-on.
 System: Home Assistant OS 11.2  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2024.1.0
 Home Assistant Supervisor: 2023.12.0

### Environment Information

Version: 

Home Assistant version:
Companion version:

Node-RED version:
Docker: no
Add-on: no

Node.js version:
OS:

**Comment by zachowj** [comment] 2024-01-04 17:13
Duplicate of #1206, #1214, #1217, #1219, #1236

https://github.com/zachowj/node-red-contrib-home-assistant-websocket#prerequisites

> This package requires Node-RED v3.1.1+

Add-on users:

https://github.com/hassio-addons/addon-node-red/issues/1767#issuecomment-1850602300

https://community.home-assistant.io/t/warning-do-not-update-websocket-to-0-61-1-with-add-on-version-16-0-2/653887/42?u=kermit

**Closed by zachowj** 2024-01-04 17:13 UTC
