### ISSUE TITLE
Calling EvoHome services triggers error: HomeAssistantError: value should be a string for dictionary value @ data['entity_id']

### ISSUE THREAD

**Issue by sgurgul** [zachowj/node-red-contrib-home-assistant-websocket#1248] opened 2024-01-07 18:14 UTC
### Describe the bug

EvoHome is a HA's build-in integration. It exposes few services to control EvoHome devices.
Home Assitant NodeRed addon version 17.0.0 introduced node-red-contrib-home-assistant-websocket update to version 0.62.2.

These update causes EvoHome services impossible to be called.
Whichever service I try I receive following error:
"HomeAssistantError: value should be a string for dictionary value @ data['entity_id']"

Calling the same service directly from HA (using Developer Tools / Services) works properly.

### To Reproduce

1. Create Call Service node
2. Configure any of EvoHome's services e.g. "evohome.set_zone_override"
3. Call the service

### Expected behavior

Executing appropriate action on EvoHome device.

### Screenshots

![image](https://github.com/zachowj/node-red-contrib-home-assistant-websocket/assets/6459421/072668d6-5346-42f1-824b-0b047afcc24f)

![image](https://github.com/zachowj/node-red-contrib-home-assistant-websocket/assets/6459421/68300b09-bfd9-4009-856e-3086436ae77b)

![image](https://github.com/zachowj/node-red-contrib-home-assistant-websocket/assets/6459421/590e7a67-5f2b-4b17-818f-d746e5c082de)

### Environment Information

Version: 

Home Assistant version: 2024.1.2

Node-RED version: 3.1.3
Docker: no
Add-on: yes, 17.0.0

### Additional context

The only workaround I found is to use websocket API node instead of "call service"

**Comment by sgurgul** [comment] 2024-01-07 18:15
Observed issue seems to be similar to #1245 
However I am not sure if root cause is the same

**Comment by zolakt** [comment] 2024-01-08 18:01
I have the same problem when calling services from the multimatic integration. In a bunch of my flows, which used to work fine before the update, I get the same error.

I can't find the root cause. What is even more weird, I tried just calling it with an inject node, no variables or anything. I don't get the error in this case, but nothing happens. The services call doesn't do anything.

The only calls that do work are those without any data...

I mean seriously, is anyone testing these updates at all? After every single node-red update half of my working flows break...

**Comment by zolakt** [comment] 2024-01-08 19:06
Btw. this definitely isn't service specific. Here is the simplest example I could think of. You can't even add an entry to the logbook. From what I've managed to conclude all service calls which have some data don't work. Only service calls without any data (e.g. light turn_on/turn_off) work.
![image](https://github.com/zachowj/node-red-contrib-home-assistant-websocket/assets/1048531/937e8f1e-16ff-41b5-8bc6-263ba71f4e64)

**Comment by sgurgul** [comment] 2024-01-08 19:10
I wouldn't be sure if it's really unspecific for the service.

I checked that before I reported this ticket and I could easily find "call service" node having some data and still working in the most recent version - not triggering this error we discuss here.

Here is a sample - light turn_on service but configured with additional data. It works and does what expected - changed the brightness of the light:
![image](https://github.com/zachowj/node-red-contrib-home-assistant-websocket/assets/6459421/e4361b50-8713-4432-bfe7-8e55354a18e0)

**Comment by sgurgul** [comment] 2024-01-08 19:12
And the workaround...
Here is a node:
![image](https://github.com/zachowj/node-red-contrib-home-assistant-websocket/assets/6459421/67ede599-c960-438f-8a12-70d1b84b77a1)
and a sample configuration - data field content:
`
{
   "type": "execute_script",
   "sequence": [
       {
           "service": "evohome.set_zone_override",
           "data": {
               "entity_id": "climate.salon",
               "setpoint": msg.payload
            }
        }
    ]
}
`

**Comment by zolakt** [comment] 2024-01-08 19:19
> I checked that before I reported this ticket and I could easily find "call service" node having some data and still working in the most recent version - not triggering this error we discuss here.

Hmm, weird... Are you sure that they actually do work, and not just "not produce an error"? I have similar examples that don't produce an error, but they don't do anything, e.g. the temperature isn't set. It used to work perfectly before the update. And it works perfectly fine when I call this service from Developer tools -> Services. I really doubt this is service specific
![image](https://github.com/zachowj/node-red-contrib-home-assistant-websocket/assets/1048531/ff3e2e2f-1e93-447b-a162-f45c033f05c0)

**Comment by sgurgul** [comment] 2024-01-08 19:22
Well, I see that light in front of me. It's changing brightness, definitely :)

**Comment by zolakt** [comment] 2024-01-08 19:30
I can confirm that it isn't even data related. Here is another example. I've done the "set_veto" call with the API node (btw. thank you for that). Now I'm testing removing the veto. It doesn't have any data, it doesn't produce any errors... but it does nothing.

I suspect this might be related to having climate entities as target. Both your and mine examples are for climate entities, even my logbook one. Just perfect for the middle of the heating season...
![image](https://github.com/zachowj/node-red-contrib-home-assistant-websocket/assets/1048531/814eabce-66ce-49b9-a754-4da0e89dc56a)

**Comment by zachowj** [comment] 2024-01-08 19:35
It has to do with the service that is being called doesn't accept entity ids as an array. A temporary workaround is to put the entity ID in the data field `{"entity_id": "light.kitchen"}`

**Comment by zolakt** [comment] 2024-01-08 19:45
> It has to do with the service that is being called doesn't accept entity ids as an array. A temporary workaround is to put the entity ID in the data field `{"entity_id": "light.kitchen"}`

Thanks. That workaround seems to work.

Do you know when a fix can be expected? I have a bunch of heating automations, none of them are working currently. It's a pretty big pain to switch all of them to the workaround and then back. If the fix will be released in the next HA update, I'll rather wait for it and operate them manually for the next 3-4 days

**Closed** 2024-01-09 02:43 UTC

**Comment by sgurgul** [comment] 2024-01-09 07:55
Great, thank you very much for prompt fix. I confirm - it works well.
