### ISSUE TITLE
Connection closed to http://supervisor/core 

### ISSUE THREAD

**Issue by MRobi1** [zachowj/node-red-contrib-home-assistant-websocket#796] opened 2022-12-06 01:17 UTC
### Describe the bug

Since latest update, continuously running into connection issues. Unsure if this is related to HA 2022.11.X or Node Red 13.5.X although based on other issues with this release of NR, I am leaning towards the issue being on NR's side.

After initially updating Node Red, the add-on would not start. Same issue as https://github.com/hassio-addons/addon-node-red/issues/1479 although in my case it was getting hung up on g++ so removing that from system_packages allowed it to boot.

Then I was not able to update or install any packages using the palette. Same error as seen https://github.com/hassio-addons/addon-node-red/issues/1478. Renaming the node-red-node-email folder then allowed me to update nodes through the palette, one of which was node-red-contrib-home-assistant-websocket to 0.47.0

Now, once per day Node Red is going into an endless connection loop. It can connect/reconnect every few seconds for hours if left without ever getting stable again. To fix I simply have to restart the Node Red addon and it starts right back up and stays connected until some random point the next day.

```
18 Nov 17:27:58 - [error] [api-call-service:Set Temp 19] Call-Service attempted without connection to server.
18 Nov 17:28:02 - [info] [server:Home Assistant] Connecting to http://supervisor/core
18 Nov 17:28:02 - [info] [server:Home Assistant] Connected to http://supervisor/core
18 Nov 17:28:05 - [info] [server:Home Assistant] Connection closed to http://supervisor/core
18 Nov 17:28:10 - [info] [server:Home Assistant] Connecting to http://supervisor/core
18 Nov 17:28:10 - [info] [server:Home Assistant] Connected to http://supervisor/core
18 Nov 17:28:13 - [info] [server:Home Assistant] Connection closed to http://supervisor/core
18 Nov 17:28:18 - [info] [server:Home Assistant] Connecting to http://supervisor/core
18 Nov 17:28:18 - [info] [server:Home Assistant] Connected to http://supervisor/core
18 Nov 17:28:20 - [info] [server:Home Assistant] Connection closed to http://supervisor/core
18 Nov 17:28:25 - [info] [server:Home Assistant] Connecting to http://supervisor/core
18 Nov 17:28:26 - [info] [server:Home Assistant] Connected to http://supervisor/core
18 Nov 17:28:26 - [info] [server:Home Assistant] Connection closed to http://supervisor/core
```

I came across a similar issue https://github.com/hassio-addons/addon-node-red/issues/1467 where the issue was being caused by the known_devices.yaml file getting swamped with bluetooth devices and thousands of lines. I checked mine which only had a total of 31 devices and around 200 lines, but I tried the proposed solution of deleting the file and rebooting HA. My known devices file was rebuilt by the system and now has only 12 devices and 84 lines. But my connection loop issue keeps reoccuring.

It was suggested in the HA NR addon repo that I try here for help. I do have an open issue there https://github.com/hassio-addons/addon-node-red/issues/1498 but no response in 2 weeks.

### This package's version (not the Home Assistant add-on version)

0.47.0

### Is Node-RED running in Docker?

Home Assistant add-on

### Node-RED version

13.5.3

### Node.js version

0.0.0.0

**Comment by zachowj** [comment] 2022-12-06 01:37
Check the HA server config in NR and make sure the "I use the add on" is checked

**Comment by MRobi1** [comment] 2022-12-06 01:40
> Check the HA server config in NR and make sure the "I use the add on" is checked

Yes, it's checked.

I should add I've been using the add on for several years. Haven't made any new flows in quite some time so I can't really point to a recent change in config or new flow. This just started out of the blue.

**Comment by zachowj** [comment] 2022-12-06 01:52
What shows in your HA log at the time of all the disconnects/reconnects?

**Comment by jsp196** [comment] 2022-12-09 19:42
I am having this same issue.  With the same thing in the HA logs.  If I make a minor change to a flow and redeploy, it works for a while, then stops working again after a couple hours.  I've tried removing the HA Add-On, the HA Integration, and making sure the Websocket add-on for NodeRed is up-to-date.  None of that fixes the problem.

`Dec 10:44:20 - [error] [api-call-service:11b150b1e2a27ac8] Call-Service attempted without connection to server.
9 Dec 10:44:24 - [info] [server:Home Assistant] Connecting to http://supervisor/core
9 Dec 10:44:24 - [info] [server:Home Assistant] Connected to http://supervisor/core
9 Dec 10:44:24 - [info] [server:Home Assistant] Connection closed to http://supervisor/core
9 Dec 10:44:24 - [info] [server:Home Assistant] Connection closed to http://supervisor/core
9 Dec 10:44:25 - [error] [api-call-service:11b150b1e2a27ac8] Call-Service attempted without connection to server.
9 Dec 10:44:29 - [info] [server:Home Assistant] Connecting to http://supervisor/core
9 Dec 10:44:29 - [info] [server:Home Assistant] Connected to http://supervisor/core
9 Dec 10:44:30 - [info] [server:Home Assistant] Connection closed to http://supervisor/core
9 Dec 10:44:30 - [info] [server:Home Assistant] Connection closed to http://supervisor/core`

**Comment by MRobi1** [comment] 2022-12-26 01:17
> What shows in your HA log at the time of all the disconnects/reconnects?

So as randomly as my issue started, it stopped and everything worked perfect for a good 2.5 weeks. And then on the 23rd it started again. 

I had a disconnect tonight at 8:43pm. Looking in my logs I've got a upnp failed to re-connect warning at 7:46pm and then a runner.py error for 2 of my harmony hubs at 9:07pm. So nothing in the HA logs at the time of the websocket error.

**Comment by MRobi1** [comment] 2023-01-04 19:46
I'm at a complete loss here. This can happen during the day, while nobody is home, or in the middle of the night. I know for certain while nobody is home or while everybody is sleeping that nothing should be firing. 

I've started moving my automations out of node-red and into native HA because I can't deal with daily node-red websocket issues :(

**Comment by meanmrgreen** [comment] 2023-02-01 13:21
I battled this issue aswell. 
And for me i found the problem to be the unifi-gateway custom integration that have a sensor that shows all your alerts. 

Problem is that these alerts don't show up in the new ui unifi controller and so it turned out unifi had logged thousands of l33t hax0rz trying to poke at my network. 

Homeassistant tried to push this sensor to node-red and the data was to much to handle. 

So i removed this sensor from the integration and the connection problem stopped immediately.

**Comment by rlust** [comment] 2023-02-02 14:26
Still having disconnects, I have about 15 switch nodes connected and they constantly are unavailable.

**Comment by MRobi1** [comment] 2023-02-06 22:52
I bit the bullet and moved everything to HA Automations. I couldn't handle my wife complaining anymore when something randomly didn't work as expected. It was a total pain to move years of flows over but I did it. As I was doing it I was disabling flows. I got to the point where every flow in NR was disabled so there is nothing being executed at all right now. And even with no flows enabled, I'm STILL getting this connection error within 24hrs of the addon starting.

**Comment by zachowj** [comment] 2023-02-06 22:59
> What shows in your HA log at the time of all the disconnects/reconnects?

I never got a response to this question.

Also, are you running the latest release? There was a fix that was added to solve an issue with the websocket queue being overloaded due to the number of entities in HA.

**Comment by MRobi1** [comment] 2023-02-06 23:15
Addon is currently on 14.0.2 and node-red-contrib-home-assistant-websocket is 0.48.1
Neither show updates available.

As for the HA logs, at the times the disconnects happen I don't see any entries in the HA logs. I did see the logitech integration also throwing websocket errors but it's been a while since I've seen that come up.

**Comment by drygnet** [comment] 2023-02-13 20:37
I have disabled most of my flows in node red and only have a powersaver-entity exposed to HA.
That entity updates every hour so can not be the reason for broken data sent over the websocket at other times.

Supervisor logs this:
`23-02-13 21:20:23 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API connection is closed
23-02-13 21:20:28 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize
23-02-13 21:20:28 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_nodered
23-02-13 21:20:28 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running
23-02-13 21:20:28 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API error: Received message 8:0 is not WSMsgType.TEXT
23-02-13 21:20:28 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API connection is closed
23-02-13 21:20:33 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize
23-02-13 21:20:33 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_nodered
23-02-13 21:20:33 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running
23-02-13 21:20:35 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API error: Received message 8:0 is not WSMsgType.TEXT
23-02-13 21:20:35 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API connection is closed
23-02-13 21:20:37 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize
23-02-13 21:20:37 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_nodered
23-02-13 21:20:37 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running
23-02-13 21:25:04 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API error: Received message 8:0 is not WSMsgType.TEXT
23-02-13 21:25:04 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API connection is closed
`

... until i make a redeploy in NR

**Comment by zachowj** [comment] 2023-02-13 22:32
@drygnet You can set the log level of the websocket component in HA to debug and see what message is received when this error occurs.

```yaml
logger:
  default: error
  logs:
    homeassistant.components.websocket_api: debug
    custom_components.nodered: debug
```

**Comment by MatheGeek** [comment] 2023-02-15 09:28
Hi ,
I try to figure this issue since the beginning of February.  If it might help,  I was having this connect / disconnect behavior with  Home Assistant 2023.02 core and Nodered 3.0.2  in docker.   When  I went back to  HA 2023.01.7  it looks fine.  I am running Nodered and Ha in Docker Containers on an Ubuntu Server 22.04 LTS

Then this morning  I tried to update again to  HA 2023.02  and  I disabled the Heartbeat option in the node-red-contrib-home-assistant-websocket.   So far so good.

https://user-images.githubu
![2023-02-06 10_07_18-Settings – Home Assistant](https://user-images.githubusercontent.com/77911186/218985935-d94931dc-dae5-4812-96f3-473f987e0311.jpg)

![2023-02-06 10_05_22-Settings – Home Assistant](https://user-images.githubusercontent.com/77911186/218985919-9a27a847-5cb3-456c-925c-d5d9d6104894.jpg)
sercontent.com/77911186/218985781-3c23df2c-159e-4a6a-bf5d-588e16974e24.mp4
[_nodered_logs.txt](https://github.com/zachowj/node-red-contrib-home-assistant-websocket/files/10741375/_nodered_logs.txt)

**Comment by drygnet** [comment] 2023-02-26 17:57
> @drygnet You can set the log level of the websocket component in HA to debug and see what message is received when this error occurs.
> 
> ```yaml
> logger:
>   default: error
>   logs:
>     homeassistant.components.websocket_api: debug
>     custom_components.nodered: debug
> ```

Could not find anything, mostly because the tibber integration was spamming the websocket,
so I turned off the tibber integration  and the problem seems to have disappeared  🤷🏽‍♂️

**Comment by drygnet** [comment] 2023-02-26 18:52
> > @drygnet You can set the log level of the websocket component in HA to debug and see what message is received when this error occurs.
> > ```yaml
> > logger:
> >   default: error
> >   logs:
> >     homeassistant.components.websocket_api: debug
> >     custom_components.nodered: debug
> > ```
> 
> Could not find anything, mostly because the tibber integration was spamming the websocket, so I turned off the tibber integration and the problem seems to have disappeared  🤷🏽‍♂️

And I was wrong... the problem has returned:
Attached logs
[log.log](https://github.com/zachowj/node-red-contrib-home-assistant-websocket/files/10834474/log.log)

**Comment by zachowj** [comment] 2023-03-22 01:50
@mrkvo If you can the connection type from using the supervisor proxy to a direct connection does the error still appear?

https://zachowj.github.io/node-red-contrib-home-assistant-websocket/guide/#configuration

**Comment by Anto79-ops** [comment] 2023-04-17 20:38
Hi all,

I just noticed this happening on my system as I was trying to hunt down what was causing elevated CPU usage and narrowed it down to NR.

I posted the issue [here](https://github.com/hassio-addons/addon-node-red/issues/1598) without know that this issue existed

Can I ask what a fix would be? At the moment, I have NR disabled.

I don't want to have to migrate my flows to HA if this is is known issue, with likely fix...or is something specific to user's systems?

thanks,

**Comment by xteaun** [comment] 2023-05-10 17:09
> Hi all,
> 
> I just noticed this happening on my system as I was trying to hunt down what was causing elevated CPU usage and narrowed it down to NR.
> 
> I posted the issue [here](https://github.com/hassio-addons/addon-node-red/issues/1598) without know that this issue existed
> 
> Can I ask what a fix would be? At the moment, I have NR disabled.
> 
> I don't want to have to migrate my flows to HA if this is is known issue, with likely fix...or is something specific to user's systems?
> 
> thanks,

I am having the same issue with a up to date Home Assistant and a new Node-Red-add-on-installation.

**Comment by chandlben** [comment] 2023-05-10 17:26
Well there has been zero response from anyone about this. I was able to "fix" it by disabling the "Enable Heartbeat" setting in the Home Assistant config node within Node-red. Not sure what, if any, complications that may cause but I've not seen any myself.

**Comment by sonixh** [comment] 2023-05-28 18:27
I had same issue. Just turn off ssl (if you do not have cert) and restart ALL SYSTEM (HAOS). After restart you will see Node-Red working properly. In my case: switch off and switch on power supply solved problem.

**Comment by Nutti85** [comment] 2023-05-29 20:20
> I had same issue. Just turn off ssl (if you do not have cert) and restart ALL SYSTEM (HAOS). After restart you will see Node-Red working properly. In my case: switch off and switch on power supply solved problem.

That seems to work for me as well!

**Comment by Nutti85** [comment] 2023-06-04 20:36
> > I had same issue. Just turn off ssl (if you do not have cert) and restart ALL SYSTEM (HAOS). After restart you will see Node-Red working properly. In my case: switch off and switch on power supply solved problem.
> 
> That seems to work for me as well!

Untill it didn't..

**Comment by scross01** [comment] 2023-06-05 11:45
> I was able to "fix" it by disabling the "Enable Heartbeat" setting in the Home Assistant config node within Node-red.

This fix seems to worked for me. 

I was seeing the same behaviour show in the video posted by @MatheGeek above. The constant connect/disconnect would happen for a couple of hours, and then stabilize for a couple of hours, and start up again. I was also seeing a significant spike in CPU during these times, along with a spike in local DNS requests (to pi.hole) for the homeassitant host. Another side affect of the issue was the Node-RED console log (running in docker) had grown to over 1.3GB due to all the connection log entries. After disabling the "Enable Heartbeat" I'm not seeing any extra connection logs and has been running stable for 10 hours so far.

Currently running `HA v2023.5.4`, `Node-RED v3.0.2`, `node-red-contrib-home-assistant-websocket v0.49.1`

**Comment by chupacabra71** [comment] 2023-06-13 23:31
having the same issue and neither disabling hearbeat nor turning off ssl has fixed the issue.

**Comment by jdiegmueller** [comment] 2023-06-14 19:47
> node-red-contrib-home-assistant-websocket

How large is your HA?  In my environment, the issue is being triggered by the size of the config/device_registry/list and config/entity_registry/list responses.  Apparently when they are 4MB or larger the Node-RED side of things aborts the websocket connection.  

I was able to work around this by removing enough integrations to get the responses back under 4MB.  But this is obviously not a real solution.

**Comment by chupacabra71** [comment] 2023-06-14 20:28
> > node-red-contrib-home-assistant-websocket
> 
> How large is your HA? 

Good question, it's relatively large install, but trying to trim the registry down is going to be a disaster.  

```
-rwx------  1 ha_user  staff   8.3M Jun 14 10:34 core.entity_registry
```

**Comment by m3ki** [comment] 2023-06-22 22:32
I am having the same issue my install is not that large ~200 something zwave devices.

```
core.entity_registry -- 3.4M
```

**Comment by chupacabra71** [comment] 2023-07-04 00:28
i ended up disabling the unifi network integration in HA since it creates a metric sh!t  ton of entities.  once disabled my size dropped to under 3MB and things started working again.

**Comment by m3ki** [comment] 2023-07-04 02:01
I don't have unifi integration, I do have a ton of wave devices however. I can't even trim anything at this point.

**Comment by johanschelin** [comment] 2023-07-05 20:38
I also suffer from this problem. I think the websocket size cap needs to be raised to support large installations like mine.

**Comment by m3ki** [comment] 2023-07-05 20:40
This doesn't seem to scale, maybe there is another solution to fix this? Is this a supervisor issue? I wonder if nodered is requesting all entities or something?

Our installations will only get bigger.

**Comment by PMPoulsen** [comment] 2023-07-06 05:03
The strange thing for me is that this appeared after upgrading to 2023.6.3 from 2023.5.4, (i have made no change in NR). 
So I had to revert back to 2023.5.4 and then it works fine again. This unfortunately leaves me stuck at 2023.5.4 as I cannot move all my NR automations to native HA.

Hopefully sombody can figue out what is wrong here.

**Comment by johanschelin** [comment] 2023-07-06 06:55
Also happened for me upgrading to .6 - believe it is because that version added a lot z-wave entities causing the amount of entities to be too high.

**Comment by m3ki** [comment] 2023-07-06 21:37
The issue persists on Hass 2023.7.0 as well.

**Comment by zachowj** [comment] 2023-07-10 04:35
@PMPoulsen @johanschelin @m3ki  
If you change the connection type from using the supervisor proxy to a direct connection, does the error still appear?

https://zachowj.github.io/node-red-contrib-home-assistant-websocket/guide/#configuration

**Comment by m3ki** [comment] 2023-07-10 04:43
> @PMPoulsen @johanschelin @m3ki  
> If you change the connection type from using the supervisor proxy to a direct connection, does the error still appear?
> 
> https://zachowj.github.io/node-red-contrib-home-assistant-websocket/guide/#configuration

I tried several times and wasn't able to connect, following the guide. I tried using domain name, IP etc. NR wouldn't connect. Not the same error. Simply won't connect. Not sure if I was doing something wrong. Search button wouldn't work either. NR is running as a Hass addon.

**Comment by PMPoulsen** [comment] 2023-07-10 13:09
> > @PMPoulsen @johanschelin @m3ki
> > If you change the connection type from using the supervisor proxy to a direct connection, does the error still appear?
> > https://zachowj.github.io/node-red-contrib-home-assistant-websocket/guide/#configuration
> 
> I tried several times and wasn't able to connect, following the guide. I tried using domain name, IP etc. NR wouldn't connect. Not the same error. Simply won't connect. Not sure if I was doing something wrong. Search button wouldn't work either. NR is running as a Hass addon.

When I am following the guyde and cliking the pensil I get this:
![image](https://github.com/zachowj/node-red-contrib-home-assistant-websocket/assets/46517931/8637b1e5-02c7-4e52-8776-12495d9ef361)

I does not look like the guide where url and api key is expectet.
Perhaps Iam looking at the wrong thing though.

I am using NR as an interated part of HASS as@m3ki

**Comment by m3ki** [comment] 2023-07-10 13:12
You have to uncheck "use addon"

**Comment by PMPoulsen** [comment] 2023-07-10 13:21
> You have to uncheck "use addon"

Got it, thanks

Have you been able to get it working yet?

**Comment by m3ki** [comment] 2023-07-10 15:36
> > You have to uncheck "use addon"
> 
> Got it, thanks
> 
> Have you been able to get it working yet?

No unfortunately not. I am unable to connect when using the hostname or the IP.

I've been beating my head over this for a month.

I believe node red should be using a different call to.fetch the entities as this current call won't scale.

**Comment by PMPoulsen** [comment] 2023-07-10 15:43
> > > You have to uncheck "use addon"
> > 
> > 
> > Got it, thanks
> > Have you been able to get it working yet?
> 
> No unfortunately not. I am unable to connect when using the hostname or the IP.
> 
> I've been beating my head over this for a month.
> 
> I believe node red should be using a different call to.fetch the entities as this current call won't scale.

OK Thanks.
I am a bit reluctant to throw my production system into another upgrade just to experience that it still doen't work.
Might give it a try during the coming weekend though.
So until then stuck with 2023.5.4

**Comment by m3ki** [comment] 2023-07-10 15:59
> > > > You have to uncheck "use addon"
> > > 
> > > 
> > > Got it, thanks
> > > Have you been able to get it working yet?
> > 
> > 
> > No unfortunately not. I am unable to connect when using the hostname or the IP.
> > I've been beating my head over this for a month.
> > I believe node red should be using a different call to.fetch the entities as this current call won't scale.
> 
> OK Thanks. I am a bit reluctant to throw my production system into another upgrade just to experience that it still doen't work. Might give it a try during the coming weekend though. So until then stuck with 2023.5.4

Same here, I am lucky to have a proxmox server so I keep trying new versions then reverting the whole thing back.
At the moment I am migrating my automations to native Hass, but it really sucks because I like the way nodered works.

**Comment by jdiegmueller** [comment] 2023-07-10 16:11
> @PMPoulsen @johanschelin @m3ki If you change the connection type from using the supervisor proxy to a direct connection, does the error still appear?
> 
> https://zachowj.github.io/node-red-contrib-home-assistant-websocket/guide/#configuration

I switched my setup to bypass HA supervisor and connect direct about 2 weeks ago.  Has greatly improved my situation.  NodeRED addon no longer needs to be restarted every 3-4 days.  I even successfully upgraded to 2023.7.1 over the weekened.

**Comment by m3ki** [comment] 2023-07-10 16:22
> @m3ki
> 
> > I believe node red should be using a different call to.fetch the entities as this current call won't scale.
> 
> NR use the same endpoints that the HA web UI uses. One difference between the web interface and the NR connection is that for people who use the add-on, it routes through the supervisor proxy. So I am trying to rule that out.

Hi @zachowj 

Thank you so much for your reply! Being a dev myself I wont pretend to know how this particular software works, however from what I gathered in the past month from the forum posts. I believe, there was a change to the entoty api and how the results are returned a few versions of HAss ago.

Apparently there is another call that can be used to fetch the updates as opposed to the one big call to fetch all states at once that is causing my and others' issues. 
In my case I have ~200 zwave switches in my house and other devices on top of that and it's probaly too much data that being sent over every second.
Here is a link to a forum post from a while back where someone mentions another call.
https://community.home-assistant.io/t/increase-websocket-message-size-limit-for-node-red/573463/6?u=bunkmate-powder

If there is anything we can do to test any changes etc... please let us know here.

**Comment by m3ki** [comment] 2023-07-10 16:41
So I was able to connect directly on 2023.5.4 Using the direct methond @jdiegmueller  proposed. However
My hass nodes show as "connecting" (I am using ssl). Automations seem to work.
 
<img width="216" alt="Screenshot 2023-07-10 at 11 38 25 AM" src="https://github.com/zachowj/node-red-contrib-home-assistant-websocket/assets/11491272/d3878097-1eec-4970-b044-4994ccf6e0d9">

I will now try to upgrade to the latest hass and see if it still works.

**Comment by PMPoulsen** [comment] 2023-07-10 16:47
Does this mean that the node-red-contrib-home-assistant-websocket add-on is no longer needed (and can be removed)?

@m3ki I am not using the ssl connection, plain http, maybe this makes the difference for your config

**Comment by m3ki** [comment] 2023-07-10 16:52
> Does this mean that the node-red-contrib-home-assistant-websocket add-on is no longer needed (and can be removed)?
> 
> @m3ki I am not using the ssl connection, plain http, maybe this makes the difference for your config

You need this plugin, as it provides home assistant nodes like server, etc...

**Comment by jdiegmueller** [comment] 2023-07-10 16:52
Since both you guys have referenced my setup, I thought I'd add that I too am using HTTP for the HA-NR direct connection.  My HTTPS reverse proxy is running on another server, so by leaving the HA-NR traffic as HTTP means it can stay on-box.

**Comment by m3ki** [comment] 2023-07-10 17:03
Ok some good news here:
I was able to upgrade to:
<img width="416" alt="Screenshot 2023-07-10 at 11 57 15 AM" src="https://github.com/zachowj/node-red-contrib-home-assistant-websocket/assets/11491272/08f899f3-1af6-4e6a-8efe-15530dcf68a8">

Nodered automations seem to work.
Bad news is that all nodes seem to show "connecting" as opposed to connected.
<img width="293" alt="Screenshot 2023-07-10 at 11 56 29 AM" src="https://github.com/zachowj/node-red-contrib-home-assistant-websocket/assets/11491272/d55a620a-4b58-461c-9ade-44554bb2a7b6">

Nodered logs show as connected.
<img width="801" alt="Screenshot 2023-07-10 at 11 59 55 AM" src="https://github.com/zachowj/node-red-contrib-home-assistant-websocket/assets/11491272/6568c253-a183-4b58-a552-77e9abf3ef79">

My nodered config:
<img width="487" alt="Screenshot 2023-07-10 at 12 01 51 PM" src="https://github.com/zachowj/node-red-contrib-home-assistant-websocket/assets/11491272/1ef30842-4611-406b-8724-eeae39f5e68a">

Hass SSL config:
<img width="290" alt="Screenshot 2023-07-10 at 12 03 06 PM" src="https://github.com/zachowj/node-red-contrib-home-assistant-websocket/assets/11491272/6551121a-f346-43ad-a7ec-940440156e35">


@zachowj are you able to commend on the above? what would cause this behavior?

It seems that direct connection is better, not sure if this would scale though, if our setups keep growing.

**Comment by johanschelin** [comment] 2023-07-11 08:47
Just confirming that changing to skip using HA Addon and creating long-lived token solved my issues.

**Comment by habitoti** [comment] 2023-07-15 16:49
> Just confirming that changing to skip using HA Addon and creating long-lived token solved my issues.

…for now, I suppose. Did the same, and yes: it helps for the moment. I am sure this needs addressing anyhow. I don‘t have a spectacular (albeit also not very small) setup, so I suppose a lot of people will eventually run into this issue and might not have the nerves to drill into this until they find any thread covering this at all (took me a while to get here also…)

**Comment by zachowj** [comment] 2023-07-15 17:28
Switching Node-RED from using the supervisor proxy to a direct websocket connection to Home Assistant would point me in the direction of that the supervisor proxy is the bottleneck.

Add your voices to the issue below to help it gain traction.

https://github.com/home-assistant/supervisor/issues/4392

**Comment by habitoti** [comment] 2023-07-15 18:12
Unfortunately, it just took a few hours for the connections to break again, even after switching to bypass the HA Addon…

**Comment by johanschelin** [comment] 2023-07-15 18:20
What does the Supervisor Log and NodeRedAddon Log say?
Mine has been working fine since the change, and I have roughly 10k entities.
________________________________
Från: habitoti ***@***.***>
Skickat: den 15 juli 2023 20:13
Till: zachowj/node-red-contrib-home-assistant-websocket ***@***.***>
Kopia: Johan Schelin ***@***.***>; Mention ***@***.***>
Ämne: Re: [zachowj/node-red-contrib-home-assistant-websocket] Connection closed to http://supervisor/core (Issue #796)


Unfortunately, it just took a few hours for the connections to break again, even after switching to bypass the HA Addon…

**Comment by habitoti** [comment] 2023-07-15 18:41
> What does the Supervisor Log and NodeRedAddon Log say? 
> […](#)

Supervisor log is saying nothing (which I would expect, as it’s bypassed). Node Red logs disconnects and reconnects. Where do I find the Addon log?

**Comment by johanschelin** [comment] 2023-07-15 19:32
Here


Med vänlig hälsning,
Johan Schelin
________________________________
Från: habitoti ***@***.***>
Skickat: Saturday, July 15, 2023 8:41:50 PM
Till: zachowj/node-red-contrib-home-assistant-websocket ***@***.***>
Kopia: Johan Schelin ***@***.***>; Mention ***@***.***>
Ämne: Re: [zachowj/node-red-contrib-home-assistant-websocket] Connection closed to http://supervisor/core (Issue #796)


What does the Supervisor Log and NodeRedAddon Log say?
…

Supervisor log is saying nothing (which I would expect, as it’s bypassed). Node Red logs disconnects and reconnects. Where do I find the Addon log?

**Comment by habitoti** [comment] 2023-07-15 21:25
> Here
> […](#)

Did you maybe miss a link?

**Comment by johanschelin** [comment] 2023-07-16 09:15
> > Here
> > […](#)
> 
> Did you maybe miss a link?

Sorry missed the attachment
![IMG_9059](https://github.com/zachowj/node-red-contrib-home-assistant-websocket/assets/65488934/43c86f61-abe2-4e63-b480-d41bf3ec5ff6)

**Comment by habitoti** [comment] 2023-07-16 14:12
Ah, you mean the regular node red log — as i wrote, it just logs pairs of disconnects and reconnects to the home assistant address.
Strangely, only switches are seemingly a problem. I have 20 entities synced between NodeRed and HA (boolean and numeric sensors and 5 switches). Only the switches loose connection and then (due to the nature of how I use them as inputs for control) mess up the whole flow. As an emergency measure (because I need that flow for controlling my wallbox) I replaced them tentatively with native NodeRed switches on an NR dashboard, and have no (technical) issues so far. So the other 15 sensors still properly interact with HA, just the control switches are currently on an (ugly…) NR dashboard and the HA-switches are deactivated. This is just acceptable as a very temporary workaround, as the main dashboard is a wall-mounted lovelace panel that the whole family uses to control charging modes and the monitor the whole EV-charging, which is currently broken due to this…

**Comment by zachowj** [comment] 2023-07-16 21:02
@habitoti do you happen to have more than one server config in NR?

**Comment by habitoti** [comment] 2023-07-17 04:42
> @habitoti do you happen to have more than one server config in NR?

At least the server node in the info panel just lists the one and only HA server setup.

I also have to say that my whole setup hasn‘t changed for a while and ran absolutely stable for months now. It all started completely out of the blue with the latest update lineup.

**Comment by zachowj** [comment] 2023-07-24 04:06
This should have been fixed with v0.55.0. Also, the next supervisor release will include an increase in proxy size. https://github.com/home-assistant/supervisor/pull/4443

**Closed by zachowj** 2023-07-24 04:06 UTC

**Comment by PMPoulsen** [comment] 2023-08-08 05:49
Just for your information.

I took the chance and upgraded to 2023.8.1 yesterday, where the  issue shouldhave been resolved.
So far it looks good, not having any disconnect issues despite my quite large installation.
Så perhaps the increase of the allowed message size plus not using the home assistant add on for the server but the direct connection with a token seems to do the trick

Thanks

**Comment by r0m1CH** [comment] 2023-10-13 16:16
Hi everyone.

I have a strange similar issue. 
Nodered is taking 100% CPU and it cannot stay connected to HA somehow.
It's says sending on some node, error on another and even connected when I deploy the flows.

I read the whole thread but does anyone find a correct solution ?

I'm using docker and run Node Red 3.1.0 and HA 2023.10.2

It was working well until these days...
