### ISSUE TITLE
Deprecated API warning: Calls to RED.util.evaluateJSONataExpression must include a callback

### ISSUE THREAD

**Issue by htmltiger** [zachowj/node-red-contrib-home-assistant-websocket#898] opened 2023-03-22 17:33 UTC
### Describe the bug

Just upgraded to node red 3.1.0-beta.2 but greeted with the following
```
[warn] Deprecated API warning: Calls to RED.util.evaluateJSONataExpression must include a callback. 
This will not be optional in Node-RED 4.0. Please identify the node from the following stack 
and check for an update on npm. If none is available, please notify the node author.
[warn] Error
at Object.evaluateJSONataExpression (/home/pi/.node-red/node_modules/@node-red/util/lib/util.js:777:18)
at JSONataService.evaluate (/home/pi/.node-red/node_modules/node-red-contrib-home-assistant-websocket/dist/common/services/JSONataService.js:58:39)
at TypedInputService.getValue (/home/pi/.node-red/node_modules/node-red-contrib-home-assistant-websocket/dist/common/services/TypedInputService.js:58:85)
at EventsAll.getTypedInputValue (/home/pi/.node-red/node_modules/node-red-contrib-home-assistant-websocket/dist/nodes/BaseNode.js:134:39)
at /home/pi/.node-red/node_modules/node-red-contrib-home-assistant-websocket/dist/nodes/BaseNode.js:138:32
at Array.forEach (<anonymous>)
at EventsAll.setCustomOutputs (/home/pi/.node-red/node_modules/node-red-contrib-home-assistant-websocket/dist/nodes/BaseNode.js:137:20)
at EventsAll.onHaEventsAll (/home/pi/.node-red/node_modules/node-red-contrib-home-assistant-websocket/dist/nodes/events-all/controller.js:57:18)
at EventEmitter.<anonymous> (/home/pi/.node-red/node_modules/node-red-contrib-home-assistant-websocket/dist/nodes/EventsNode.js:39:17)
at EventEmitter.emit (node:events:525:35)
at Websocket._Websocket_emitEvent (/home/pi/.node-red/node_modules/node-red-contrib-home-assistant-websocket/dist/homeAssistant/Websocket.js:394:67)
at Websocket.onClientEvents (/home/pi/.node-red/node_modules/node-red-contrib-home-assistant-websocket/dist/homeAssistant/Websocket.js:238:87)
at Object.callback (/home/pi/.node-red/node_modules/node-red-contrib-home-assistant-websocket/dist/homeAssistant/Websocket.js:143:65)
at /home/pi/.node-red/node_modules/home-assistant-js-websocket/dist/haws.cjs:236:34
at Array.forEach (<anonymous>)
at Connection._handleMessage (/home/pi/.node-red/node_modules/home-assistant-js-websocket/dist/haws.cjs:231:26)
at callListener (/home/pi/.node-red/node_modules/node-red-contrib-home-assistant-websocket/node_modules/ws/lib/event-target.js:290:14)
at WebSocket.onMessage (/home/pi/.node-red/node_modules/node-red-contrib-home-assistant-websocket/node_modules/ws/lib/event-target.js:209:9)
at WebSocket.emit (node:events:513:28)
at Receiver.receiverOnMessage (/home/pi/.node-red/node_modules/node-red-contrib-home-assistant-websocket/node_modules/ws/lib/websocket.js:1184:20)
at Receiver.emit (node:events:513:28)
at Receiver.dataMessage (/home/pi/.node-red/node_modules/node-red-contrib-home-assistant-websocket/node_modules/ws/lib/receiver.js:541:14)

```

### To Reproduce

upgraded node-red by ` npm install node-red@next`

### This package's version (not the Home Assistant add-on version)

0.49

### Is Node-RED running in Docker?

No

### Node-RED version

3.1.0-beta.2

### Node.js version

18.15.0

**Comment by bml5631** [comment] 2023-06-12 03:29
Log flooded with these...
 [warn] Deprecated API warning: Calls to RED.util.evaluateJSONataExpression must include a callback. This will not be optional in Node-RED 4.0. Please identify the node from the following stack and check for an update on npm. If none is available, please notify the node author.
11 Jun 20:23:27 - [warn] Error

**Comment by motsu35** [comment] 2023-09-07 05:57
I also updated my docker images today, and im getting the same errors. running the version of homeassistant where its a stand-alone docker image without the supervisor.

ha version is homeassistant/home-assistant:stable... which isn't super useful, so heres some image labels:
```
    "io.hass.base.image": "ghcr.io/home-assistant/amd64-base:3.18",
    "io.hass.base.name": "python",
    "io.hass.base.version": "2023.08.0",
    "io.hass.type": "core",
    "io.hass.version": "2023.9.0",
```
node-red is v3.1.0

plugin version is 0.56.1

**Comment by fire1ce** [comment] 2023-09-07 06:30
+1

**Comment by jrnas** [comment] 2023-09-07 06:34
+1 please fix that problem

**Comment by marcosandremartins** [comment] 2023-09-07 08:41
+1

**Comment by S474N** [comment] 2023-09-07 11:29
3.1.0 stable is out and same problem!

Have dockerized version with  nodejs v14.21.3

```
07. 09. 2023 13:21:52
7 Sep 13:21:52 - [warn] Error: 
07. 09. 2023 13:21:52
    at Object.evaluateJSONataExpression (/usr/src/node-red/node_modules/@node-red/util/lib/util.js:775:18)
07. 09. 2023 13:21:52
    at JSONataService.evaluate (/data/node_modules/node-red-contrib-home-assistant-websocket/dist/common/services/JSONataService.js:58:39)
07. 09. 2023 13:21:52
    at CallService.evaluateJSONata (/data/node_modules/node-red-contrib-home-assistant-websocket/dist/nodes/BaseNode.js:131:36)
07. 09. 2023 13:21:52
    at CallService.onInput (/data/node_modules/node-red-contrib-home-assistant-websocket/dist/nodes/call-service/controller.js:63:50)
07. 09. 2023 13:21:52
    at CallService.preOnInput (/data/node_modules/node-red-contrib-home-assistant-websocket/dist/nodes/BaseNode.js:208:18)
07. 09. 2023 13:21:52
    at /usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:210:26
07. 09. 2023 13:21:52
    at Object.trigger (/usr/src/node-red/node_modules/@node-red/util/lib/hooks.js:166:13)
07. 09. 2023 13:21:52
    at callServiceNode.Node._emitInput (/usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:202:11)
07. 09. 2023 13:21:52
    at callServiceNode.Node.emit (/usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:186:25)
07. 09. 2023 13:21:52
    at callServiceNode.Node.receive (/usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:494:10)
07. 09. 2023 13:21:52
    at deliverMessageToDestination (/usr/src/node-red/node_modules/@node-red/runtime/lib/flows/Flow.js:799:40)
07. 09. 2023 13:21:52
    at Immediate._onImmediate (/usr/src/node-red/node_modules/@node-red/runtime/lib/flows/Flow.js:815:21)
07. 09. 2023 13:21:52
    at processImmediate (internal/timers.js:464:21)
07. 09. 2023 13:22:17
7 Sep 13:22:17 - [warn] Deprecated API warning: Calls to RED.util.evaluateJSONataExpression must include a callback. This will not be optional in Node-RED 4.0. Please identify the node from the following stack and check for an update on npm. If none is available, please notify the node author.
07. 09. 2023 13:22:17
7 Sep 13:22:17 - [warn] Error: 
07. 09. 2023 13:22:17
    at Object.evaluateJSONataExpression (/usr/src/node-red/node_modules/@node-red/util/lib/util.js:775:18)
07. 09. 2023 13:22:17
    at JSONataService.evaluate (/data/node_modules/node-red-contrib-home-assistant-websocket/dist/common/services/JSONataService.js:58:39)
07. 09. 2023 13:22:17
    at CallService.evaluateJSONata (/data/node_modules/node-red-contrib-home-assistant-websocket/dist/nodes/BaseNode.js:131:36)
07. 09. 2023 13:22:17
    at CallService.onInput (/data/node_modules/node-red-contrib-home-assistant-websocket/dist/nodes/call-service/controller.js:63:50)
07. 09. 2023 13:22:17
    at CallService.preOnInput (/data/node_modules/node-red-contrib-home-assistant-websocket/dist/nodes/BaseNode.js:208:18)
07. 09. 2023 13:22:17
    at /usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:210:26
07. 09. 2023 13:22:17
    at Object.trigger (/usr/src/node-red/node_modules/@node-red/util/lib/hooks.js:166:13)
07. 09. 2023 13:22:17
    at callServiceNode.Node._emitInput (/usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:202:11)
07. 09. 2023 13:22:17
    at callServiceNode.Node.emit (/usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:186:25)
07. 09. 2023 13:22:17
    at callServiceNode.Node.receive (/usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:494:10)
07. 09. 2023 13:22:17
    at deliverMessageToDestination (/usr/src/node-red/node_modules/@node-red/runtime/lib/flows/Flow.js:799:40)
07. 09. 2023 13:22:17
    at Immediate._onImmediate (/usr/src/node-red/node_modules/@node-red/runtime/lib/flows/Flow.js:815:21)
07. 09. 2023 13:22:17
    at processImmediate (internal/timers.js:464:21)
07. 09. 2023 13:22:42
7 Sep 13:22:42 - [warn] Deprecated API warning: Calls to RED.util.evaluateJSONataExpression must include a callback. This will not be optional in Node-RED 4.0. Please identify the node from the following stack and check for an update on npm. If none is available, please notify the node author.
```

**Comment by Vitek-1977** [comment] 2023-09-07 12:12
+1

**Comment by zachowj** [comment] 2023-09-07 12:23
I won't have time to implement and test this until about a week from now. This doesn't stop anything from working.

**Comment by S474N** [comment] 2023-09-07 12:25
Unfortunately, it completely swallows the debug on right side.

**Comment by LubosKovar** [comment] 2023-09-07 12:27
+1 please fix it. Thanks

**Comment by Rickerdo** [comment] 2023-09-07 13:24
> This doesn't stop anything from working.

Maybe not, but it does render the debug pane useless.

**Comment by jonastaedcke** [comment] 2023-09-07 13:30
Please give your consent via emojis and not via a post.

Until the issue is resolved: Use version 3.0 and not latest with 3.1 of NodeRed
`docker pull nodered/node-red:3.0`

Thank you for @zachowj for your great work!

**Comment by zachowj** [comment] 2023-09-07 21:25
A temporary solution if you want to run version 3.1, without the log being spammed, is to comment out lines 772-775  [@node-red/util/lib/util.js](https://github.com/node-red/node-red/blob/d9bbac20f356614e4e79e83fbbed73f72779c661/packages/node_modules/%40node-red/util/lib/util.js#L772-L775) in the Node-RED source.

In the docker release, the path of the file is `/usr/src/node-red/node_modules/@node-red/util/lib/util.js`

**Comment by bml5631** [comment] 2023-09-07 22:31
> A temporary solution if you want to run version 3.1, without the log being spammed, is to comment out lines 772-775 [@node-red/util/lib/util.js](https://github.com/node-red/node-red/blob/d9bbac20f356614e4e79e83fbbed73f72779c661/packages/node_modules/%40node-red/util/lib/util.js#L772-L775) in the Node-RED source.
> 
> In the docker release, the path of the file is `/usr/src/node-red/node_modules/@node-red/util/lib/util.js`

That works. Thank you!

**Comment by sirjeannot** [comment] 2023-09-12 07:57
> /usr/src/node-red/node_modules/@node-red/util/lib/util.js

thank you, work around works 👍

**Comment by yayadrian** [comment] 2023-09-12 09:38
> In the docker release, the path of the file is `/usr/src/node-red/node_modules/@node-red/util/lib/util.js`

Yep this also worked for me Thanks!

**Comment by meironke** [comment] 2023-09-13 06:09
> A temporary solution if you want to run version 3.1, without the log being spammed, is to comment out lines 772-775 [@node-red/util/lib/util.js](https://github.com/node-red/node-red/blob/d9bbac20f356614e4e79e83fbbed73f72779c661/packages/node_modules/%40node-red/util/lib/util.js#L772-L775) in the Node-RED source.
> 
> In the docker release, the path of the file is `/usr/src/node-red/node_modules/@node-red/util/lib/util.js`

Thanks for the quick fix. May I ask you to quickly drop the lines here that you have commented out?
I have a docker installation and don't have the folder /usr/src/node-red/node_modules/**@node-red**/.

Thank you so much!

**Comment by S474N** [comment] 2023-09-13 08:45
@meironke you have, inside of container!

`docker exec -it nodered bash`

**Comment by figorr** [comment] 2023-09-13 19:58
Is there any temporary solution to avoid log being spammed if we are using the node-red addon from supervisor? I could downgrade to a previous addon version, 14.4.5 instead of using the new 14.5.0, using an old backup.

**Comment by mmaritz** [comment] 2023-09-14 04:04
> Log flooded with these... [warn] Deprecated API warning: Calls to RED.util.evaluateJSONataExpression must include a callback. This will not be optional in Node-RED 4.0. Please identify the node from the following stack and check for an update on npm. If none is available, please notify the node author. 11 Jun 20:23:27 - [warn] Error

+1

**Comment by mraita** [comment] 2023-09-14 09:25
+1

**Comment by stroodl3bug** [comment] 2023-09-14 12:38
> @meironke you have, inside of container!
> 
> `docker exec -it nodered bash`

if its within the addon, may need to replace "nodered" with the output of this command

`docker ps --format '{{.Names}}' | grep nodered`

**Comment by lougreenwood** [comment] 2023-09-14 13:23
After updating the file in the docker container & saving it does one need to also restart node red? I commented out the lines and restarted the addon, but the lines were uncommented out. So I assume that I need to restart the node red process in the docker instance so it picks up the change?

**Comment by mmaritz** [comment] 2023-09-14 14:37
> After updating the file in the docker container & saving it does one need to also restart node red? I commented out the lines and restarted the addon, but the lines were back/no longer commented out.
> 
> So I assume that I need to restart the node red process in the docker instance so it picks up the change?
> 
> Edit:
> 
> Also, for me, the file was at `/opt/node_modules/\@node-red/util/lib/util.js`... `/usr/src` doesn't exist for me.

I also have the same issue.  Is there no way to push an update to the [node-red-contrib-home-assistant-websocket](https://github.com/zachowj/node-red-contrib-home-assistant-websocket) so this can be done cleanly.   Until the real issue is resolved.

**Comment by Mithrox** [comment] 2023-09-14 14:42
I can see there is a workaround for those running Node Red as a docker install, but for me who has it as an Addon in HA core install, is that an option?

**Comment by mmaritz** [comment] 2023-09-14 15:00
> I can see there is a workaround for those running Node Red as a docker install, but for me who has it as an Addon in HA core install, is that an option?

+1

**Comment by Brain1000** [comment] 2023-09-14 15:05
> I can see there is a workaround for those running Node Red as a docker install, but for me who has it as an Addon in HA core install, is that an option?

+1

**Comment by reicharb** [comment] 2023-09-14 16:48
I am also running Addon in HA on a Blue and I can't find that file at all.

**Comment by fixx-er** [comment] 2023-09-14 19:25
dang I wish I knew how to get an editor to edit this file. apt-get doeskin work, nano and vim isnt installed, and I tried to do a remote edit, but I dont know how.

**Comment by scenotto** [comment] 2023-09-14 20:12
try this:
vi util.js

i to enter insert mode
comment out the lines
Esc key to exit insert mode

:w + enter to write the changes
:x + enter to exit VI

**Comment by scenotto** [comment] 2023-09-14 20:12
> dang I wish I knew how to get an editor to edit this file.

try this:
vi util.js

i to enter insert mode
comment out the lines
Esc key to exit insert mode

:w + enter to write the changes
:x + enter to exit VI

**Comment by henriklund** [comment] 2023-09-14 20:21
And to go to proper line:

- press ESC key
- Type 772 (nothing is displayed - that is OK)
- Press SHIFT and g simultaneously (for goto)

**Comment by fixx-er** [comment] 2023-09-14 20:35
Its been a long time since I have used VI.  and to insert a comment.
I followed the example above the code for comment out using  '*'

LOL
so after verifying the change was made, I restart node-red and the lines 772-775 are uncommented again
:)

**Comment by jzielke84** [comment] 2023-09-14 20:45
Guys what you are doing doesn't work. If the add-on is restarted, the change is reverted, since it's not on a mounted path outside of the docker image. So every time you restart node-red or ha, the change get's reverted.

**Comment by jzielke84** [comment] 2023-09-14 20:55
Sorry, my previous statement was false about the docker state (I've mixed up things). I guess the node-red app overwrites some files upon restart (maybe unpacking something every time). Anyway, there seems to be no fix for this issue but just using a backup and never click the nasty update button 😄

**Comment by jzielke84** [comment] 2023-09-14 21:06
I've found a fix for the supervisor setup:

1. Open `/opt/hassio/addons.json` on the host machine with your editor of preference
2. Search for `14.5.0` and replace it with `14.4.5` (it should appear two times in the file)
3. Save and exit the editor
4. Reboot the whole host machine (restarting ha won't work)
5. Now node-red should be in the old version

**Comment by Mithrox** [comment] 2023-09-14 21:09
> I've found a fix for the supervisor setup:
> 
> 1. Open `/opt/hassio/addons.json` on the host machine with your editor of preference
> 2. Search for `14.5.0` and replace it with `14.4.5` (it should appear two times in the file)
> 3. Save and exit the editor
> 4. Reboot the whole host machine (restarting ha won't work)
> 5. Now node-red should be in the old version
> 6. Homeassistant will ask you to update the add-on - Don't 😄

I logged on my HA NUC with root but in /opt there is nothing, no /hassio folder and thus nothing under it. Do you do anything special to find it, I tried both su root and su - after logging in, but since I am in as root there should not be any need for it. Sorry if this is clear as day for everyone but me, but I am a bit lost :)

**Comment by jzielke84** [comment] 2023-09-14 21:17
> I logged on my HA NUC with root but in /opt there is nothing, no /hassio folder and thus nothing under it. Do you do anything special to find it, I tried both su root and su - after logging in, but since I am in as root there should not be any need for it. Sorry if this is clear as day for everyone but me, but I am a bit lost :)

Whops, right, I've symlinked something for convenience ;-) It should reside here `/usr/share/hassio/addons.json`.

Otherwise you may also find it by using the following command:

```shell
find / -type f -name "addons.json"
```

**Comment by fixx-er** [comment] 2023-09-14 21:51
yes -  restore 14.4.5 from back up and you have to do a complete restart of system.

________________________________

**Comment by fixx-er** [comment] 2023-09-14 21:52
you know this makes total sense if we docker is reloading an image.  I wish I would have thought of that.
________________________________

**Comment by jzielke84** [comment] 2023-09-14 21:54
> yes - restore 14.4.5 from back up and you have to do a complete restart of system.
> […](#)

Right, I haven’t thought about that. Much better than fiddling with files. 👍

**Comment by S-E-B-123** [comment] 2023-09-14 22:25
Hi,
maybe i found a workaround for users of the NR-Addon. Put the following line in the config page of the Addon in the section `init_commands` 

`sed -i "772,775d" node_modules/@node-red/util/lib/util.js`

**Comment by kevinschmidt86** [comment] 2023-09-14 23:41
> Hi, maybe i found a workaround for users of the NR-Addon. Put the following line in the config page of the Addon in the section `init_commands` and restart the addon.
> 
> `sed -i "772,775d" node_modules/@node-red/util/lib/util.js`

Worked for me, except I had to add "/opt/" the string, resulting in the following:  "sed -i "772,775d" /opt/node_modules/@node-red/util/lib/util.js"

**Comment by Psythian** [comment] 2023-09-14 23:55
Thanks @kevinschmidt86 that was exactly what I needed. It fixed it for me too.

**Comment by fixx-er** [comment] 2023-09-15 00:09
it works! :+1:

**Comment by Mithrox** [comment] 2023-09-15 05:19
This is a bit weird, I cannot find addons.json anywhere, there is no hassio folder under /usr/share either.

And I did try to the command above here, with no result

![image](https://github.com/zachowj/node-red-contrib-home-assistant-websocket/assets/58890682/ea9c3323-bdd9-47a3-bf55-1a7d55e50dd9)

**Comment by henriklund** [comment] 2023-09-15 05:31
Try to see if you can find it using:
`find . -name util.js -type f -exec grep -i "RED.util.evaluateJSONataExpression" '{}' \; -print`

**Comment by Mithrox** [comment] 2023-09-15 05:35
I did not find it using the command above (also tried / instead of . to make sure (I think you have edited the post now after I copied it).

![image](https://github.com/zachowj/node-red-contrib-home-assistant-websocket/assets/58890682/7a521be8-011e-411a-8ac1-2d3a1ff2f93d)

However, I did put in the text in the init_commands and it seems to have solved it, no more error messages coming at this time.

Just so I understand, this is a warning of usage that won't work in the next major version, correct? Is it the nodes that need to be recreated in another way, or is it something else manually we need to do to circumvent the problem before the big upgrade?

**Comment by henriklund** [comment] 2023-09-15 05:46
You are right about the '.' -> '/' edit.

This is a warning of something not going to work in NodeRED v4. The offending piece of software is the HA websocket. That needs to be corrected in order for the warning to disappear. The deletion of the four lines is a workaround to remove the warning from sight. I'm definitely going to remove the init_command above before upgrading to the next version of NodeRED (who know what could mistakenly be deleted then), and also try to remove it when there is a new version of the websocket

**Comment by GroundAttack** [comment] 2023-09-15 17:34
> sed -i "772,775d" /opt/node_modules/@node-red/util/lib/util.js

Great stuff! Works a treat.

**Comment by Aaroneisele55** [comment] 2023-09-16 11:34
I also have it:
`Error: 
    at Object.evaluateJSONataExpression (/opt/node_modules/@node-red/util/lib/util.js:775:18)
    at JSONataService.evaluate (/opt/node_modules/node-red-contrib-home-assistant-websocket/dist/common/services/JSONataService.js:58:39)
    at CallService.evaluateJSONata (/opt/node_modules/node-red-contrib-home-assistant-websocket/dist/nodes/BaseNode.js:131:36)
    at CallService.onInput (/opt/node_modules/node-red-contrib-home-assistant-websocket/dist/nodes/call-service/controller.js:63:50)
    at CallService.preOnInput (/opt/node_modules/node-red-contrib-home-assistant-websocket/dist/nodes/BaseNode.js:208:18)
    at /opt/node_modules/@node-red/runtime/lib/nodes/Node.js:210:26
    at Object.trigger (/opt/node_modules/@node-red/util/lib/hooks.js:166:13)
    at callServiceNode.Node._emitInput (/opt/node_modules/@node-red/runtime/lib/nodes/Node.js:202:11)
    at callServiceNode.Node.emit (/opt/node_modules/@node-red/runtime/lib/nodes/Node.js:186:25)
    at callServiceNode.Node.receive...`

I then added `sed -i "772,775d" /opt/node_modules/@node-red/util/lib/util.js` to my init_commands and it now works.
This is really not the solution but it is at least a wrokaround until the node gets fixed.

**Comment by neil1111** [comment] 2023-09-16 14:57
Hi. Per posts by me and others on the NR discord channel, this issue results in the Events-All node that checks for event type=zwave_js_value_notification results in this error. 
Version: HAOS 2023.9.2
HA Addon: 14.5.0
Error resolves after restoring addon 14.4.5 (still under 2023.9.2)

Here's the errors appearing the the Debug node. I'm happy to do any testing if it would be helpful. Just tag me here or on discord as @ha_tinkerer.

"Deprecated API warning: Calls to RED.util.evaluateJSONataExpression must include a callback. This will not be optional in Node-RED 4.0. Please identify the node from the following stack and check for an update on npm. If none is available, please notify the node author."

Error: 
    at Object.evaluateJSONataExpression (/opt/node_modules/@node-red/util/lib/util.js:775:18)
    at JSONataService.evaluate (/config/node-red/node_modules/node-red-contrib-home-assistant-websocket/dist/common/services/JSONataService.js:58:39)
    at TypedInputService.getValue (/config/node-red/node_modules/node-red-contrib-home-assistant-websocket/dist/common/services/TypedInputService.js:58:85)
    at EventsAll.getTypedInputValue (/config/node-red/node_modules/node-red-contrib-home-assistant-websocket/dist/nodes/BaseNode.js:134:39)
    at /config/node-red/node_modules/node-red-contrib-home-assistant-websocket/dist/nodes/BaseNode.js:138:32
    at Array.forEach (<anonymous>)
    at EventsAll.setCustomOutputs (/config/node-red/node_modules/node-red-contrib-home-assistant-websocket/dist/nodes/BaseNode.js:137:20)
    at EventsAll.onHaEventsAll (/config/node-red/node_modules/node-red-contrib-home-assistant-websocket/dist/nodes/events-all/controller.js:57:18)
    at EventEmitter.<an...

Everything is fine at Zwave, which properly includes the following in the logs:
2023-09-16 10:52:14.052 INFO Z-WAVE: [Node 031] Value notification: 91-0-scene-002 0
2023-09-16T14:52:14.055Z CNTRLR « [Node 031] received CentralScene notification {
                                      "nodeId": 31,
                                      "ccId": "Central Scene",
                                      "ccCommand": "0x03",
                                      "payload": "0x438002"
                                  }
2023-09-16 10:52:14.098 INFO Z-WAVE: [Node 031] Value updated: 38-0-targetValue 99 => 0
2023-09-16 10:52:14.110 INFO Z-WAVE: [Node 031] Value updated: 38-0-duration 0s => 0s
2023-09-16 10:52:14.112 INFO Z-WAVE: [Node 031] Value updated: 38-0-currentValue 99 => 0

**Comment by Exit2Studios** [comment] 2023-09-17 21:30
I have the same error

**Comment by meironke** [comment] 2023-09-18 09:14
> @meironke you have, inside of container!
> 
> `docker exec -it nodered bash`

Works like a charm! Thank you!

I thought it would be in the 'data' folder, but it is not! Here's a detailed "how to".

1. `docker exec -it nodered bash`  #if your container is called "nodered" and not "nodered_prod_orWhatEver"
2. `nano node_modules/@node-red/util/lib/util.js`
3. `CTRL-Q` and seach for "Deprecated API"
4. Comment out the lines with `//`

Should look like this then (without the colors).
![2023-09-18 11_06_55-● util js - ingo  SSH_ nuc  - Visual Studio Code](https://github.com/zachowj/node-red-contrib-home-assistant-websocket/assets/56265223/3ac8c587-1a9b-42ab-8a0d-ec3ff948e474)

**Comment by mraita** [comment] 2023-09-18 09:15
> Hi, maybe i found a workaround for users of the NR-Addon. Put the following line in the config page of the Addon in the section `init_commands` and restart the addon.
> 
> `sed -i "772,775d" /opt/node_modules/@node-red/util/lib/util.js`
> 
> ( added missing `/opt/` thx @kevinschmidt86 )

Problem temporary solved. Please read the Thread !!!

**Comment by jagradang** [comment] 2023-09-18 09:29
> > Hi, maybe i found a workaround for users of the NR-Addon. Put the following line in the config page of the Addon in the section `init_commands` and restart the addon.
> > `sed -i "772,775d" /opt/node_modules/@node-red/util/lib/util.js`
> > ( added missing `/opt/` thx @kevinschmidt86 )
> 
> Problem temporary solved. Please read the Thread !!!

Maybe you need to read my reply before meaninglessly down voting my post - I use node red inside Home assistant so i cant use this "work around".

**Comment by jagradang** [comment] 2023-09-18 09:32
> > Hi, maybe i found a workaround for users of the NR-Addon. Put the following line in the config page of the Addon in the section `init_commands` and restart the addon.
> > `sed -i "772,775d" /opt/node_modules/@node-red/util/lib/util.js`
> > ( added missing `/opt/` thx @kevinschmidt86 )
> 
> Problem temporary solved. Please read the Thread !!!

A temporary hack is not a FIX - I asked when will this be "FIXED".  no reason to downvote the post?

**Comment by mraita** [comment] 2023-09-18 09:33
> > > Hi, maybe i found a workaround for users of the NR-Addon. Put the following line in the config page of the Addon in the section `init_commands` and restart the addon.
> > > `sed -i "772,775d" /opt/node_modules/@node-red/util/lib/util.js`
> > > ( added missing `/opt/` thx @kevinschmidt86 )
> > 
> > 
> > Problem temporary solved. Please read the Thread !!!
> 
> Maybe you need to read my reply before meaninglessly down voting my post - I use node red inside Home assistant so i cant use this "work around".

I use it also in HA and it work for me ant the other Addon Users.

**Comment by Mithrox** [comment] 2023-09-18 09:35
> 
> A temporary hack is not a FIX - I asked when will this be "FIXED". no reason to downvote the post?
The issue is a warning of something that will happen in the next major version of NR, at that point the nodes/calls will need to be done differently. The temporary fix is solving THIS problem, as the thread is about. It removes all those spamming warnings in your debug window. The thread has the fix both for those running NR in a container, and for those of us who run it as an addon in HA. So the "problem" is solved by this thread, but there should be changes done before NR 4.0 comes out.

**Comment by bernardesarthur** [comment] 2023-09-18 12:15
Guys, please see this: https://github.com/zachowj/node-red-contrib-home-assistant-websocket/pull/1063

**Closed** 2023-09-24 05:26 UTC
Labels: Type: Bug

**Comment by andy-brandt** [comment] 2023-09-25 02:42
Please fix

**Comment by andy-brandt** [comment] 2023-09-25 02:53
> > Hi, maybe i found a workaround for users of the NR-Addon. Put the following line in the config page of the Addon in the section `init_commands` and restart the addon.
> > `sed -i "772,775d" node_modules/@node-red/util/lib/util.js`
> 
> Worked for me, except I had to add "/opt/" the string, resulting in the following: "sed -i "772,775d" /opt/node_modules/@node-red/util/lib/util.js"

Worked for me!  Thank you so much!

**Comment by henriklund** [comment] 2023-09-25 19:18
> Adding another vote to fix this. The debug window is useless with these warnings constantly filling it up.

Please check [1063](https://github.com/zachowj/node-red-contrib-home-assistant-websocket/pull/1063) (already mentioned last week - see a few posts ago). This is now just awaiting the normal release pipeline.

**Comment by Ferrari2** [comment] 2023-09-25 19:34
It seems the Node Red guys are out of control in this case - and that is really really bad for the node red society.

I unfortunately think, I now have to change away from the ever changing node red to the build in action controls of Home Assistant.

**Comment by Mithrox** [comment] 2023-09-25 20:05
> It seems the Node Red guys are out of control in this case - and that is really really bad for the node red society.
> 
> I unfortunately think, I now have to change away from the ever changing node red to the build in action controls of Home Assistant.

First off, I don't really know what you're referring to when you say "out of control", I've used Node Red a lot the last 2 years, and this is the only issue I have ever had. Second, you can just implement the fix over, it takes 10 seconds and then you restart the add-on, problem solved. When it's changed in NR add-on/nodes you can just remove the line again from your configuration. I think you're making this into a much bigger thing than it has to, but if you want to move all your automations over to native Home Assistant, go ahead. You either have very simple automations, or you have way too much time on your hands. Node Red wins hands down any day of the week in simplicity and flexibility.

**Comment by zachowj** [comment] 2023-09-25 20:15
This issue has been fixed and will be in the next release.

This issue never stopped the Home Assistant nodes from working correctly, it was just an annoyance. Solutions to remove this annoyance have been posted above in this issue.

**Comment by zachowj** [comment] 2023-09-26 20:16
Beta released https://github.com/zachowj/node-red-contrib-home-assistant-websocket/releases/tag/v0.57.0-beta.1
