### ISSUE TITLE
Restarting NodeRed deletes node-red-contrib-home-assistant-websocket

### ISSUE THREAD

**Issue by ingo916** [zachowj/node-red-contrib-home-assistant-websocket#1236] opened 2024-01-02 02:57 UTC
### Describe the bug

Installed node-red-contrib-home-assistant-websocket when restarting home assistant node red companion app node-red-contrib-home-assistant-websocket is no longer installed

### Expected behavior

Restarting Home Assistant no red companion app should not delete node-red-contrib-home-assistant-websocket

### Screenshots

![IMG_0116](https://github.com/zachowj/node-red-contrib-home-assistant-websocket/assets/41309095/1844c78d-7528-4f77-8453-ab0ab86029a3)

### Environment Information

Version: 
Core
2023.12.4
Supervisor
2023.12.0
Operating System
11.2
Frontend
20231208.2

Node-RED 
Current version: 16.0.2

node-red-contrib-home-assistant-websocket
0.59.0 and 0.62.2

**Comment by zachowj** [comment] 2024-01-02 03:00
Duplicate of https://github.com/zachowj/node-red-contrib-home-assistant-websocket/issues/1206, https://github.com/zachowj/node-red-contrib-home-assistant-websocket/issues/1214, https://github.com/zachowj/node-red-contrib-home-assistant-websocket/issues/1217, #1219

https://github.com/zachowj/node-red-contrib-home-assistant-websocket#prerequisites

**Closed by zachowj** 2024-01-02 03:00 UTC
