### ISSUE TITLE
Allow Current State Node If State to be converted to boolean from on/off without forcing the State Type to boolean.

### ISSUE THREAD

**Issue by niemyjski** [zachowj/node-red-contrib-home-assistant-websocket#176] opened 2019-12-26 14:47 UTC
I'm using latest stable of hassio + nodered. I have an input boolean that I check to see if I should enable all my automations. I noticed that the state type is correctly converted to boolean but the if state condition type is always evaluated to a string so when the expression is evaluated it's check `!!condition` is always true. I believe the correct behavior would be to set the if state condition type to the same state type we are converting too (currently state type is converted to a boolean but the if state condition is treated as a string.

![image](https://user-images.githubusercontent.com/1020579/71479945-50229500-27bc-11ea-8813-f9807048b12c.png)

Update: This is fixed, however it would be really nice to use Boolean logic on the If State without changing the state type to boolean. Should I create a new issue or update the description on this one?

**Comment by niemyjski** [comment] 2019-12-26 14:48
Also it would be really nice if you change the state type to boolean maybe the if statement just becomes a checkbox or number field.

**Comment by zachowj** [comment] 2019-12-27 05:13
Based on the screenshot I would say you're not using the latest release of this package. I don't use hass.io but my guess would be your using a version from around the time that ingress was added to the Node-RED add-on. What version does the NR palette manager say is installed?

The current version of this package should show something like this when you're editing the current-state node.

![image](https://user-images.githubusercontent.com/37859597/71502330-7845de80-2824-11ea-94c1-81bf05221bf9.png)

**Comment by niemyjski** [comment] 2019-12-31 00:43
It says 0.10.2 is the version I'm using.

**Comment by niemyjski** [comment] 2019-12-31 00:46
Yeah I'm way out of date. I gotta figure out why this isn't being updated by the hassio package.

**Comment by niemyjski** [comment] 2019-12-31 03:22
This is fixed, however it would be really nice to use Boolean logic on the If State without changing the state type to boolean. Should I create a new issue or update the description on this one?

**Comment by zachowj** [comment] 2019-12-31 04:09
I don't understand exactly what you're asking for? Have an example?

**Comment by zachowj** [comment] 2020-01-18 15:19
duplicate of #197

**Closed by zachowj** 2020-01-18 15:19 UTC
