### ISSUE TITLE
Flows showing n/a

### ISSUE THREAD

**Issue by Wibias** [zachowj/node-red-contrib-home-assistant-websocket#226] opened 2020-03-30 23:10 UTC
### Describe the bug

The bug showing "NAN" on the nodes "events: state" and "current state" is still there.

### To Reproduce

Upgrade from 0.22.0 to 0.22.1

### Expected behavior

Clean upgrade with no issues.

### Screenshots

![image](https://user-images.githubusercontent.com/37517432/77970279-10ec6e80-72ec-11ea-8dab-00e043048716.png)

### Example Flow

n/a

### Environment (please complete the following information):

- Node Red Version: 1.0.4
- Node.js Version: 10.19.0
- NR Home Assistant Plugin Version: n/a
- Is Node Red running in Docker: yes

### Other (please complete the following information):

Yes

### Additional context

n/a

**Comment by zachowj** [comment] 2020-03-30 23:25
Do all nodes show the status of `NaN`? Do you have the `State Type` set to something other than `string`?

**Comment by Wibias** [comment] 2020-03-30 23:37
![image](https://user-images.githubusercontent.com/37517432/77971819-fddb9d80-72ef-11ea-9824-456ff4fd9933.png)

These are the ones I am able to test. State Type is empty in this example. In the picture where I created the Issue the state types are just strings e. x. "triggered".

**Comment by Wibias** [comment] 2020-03-30 23:49
I have a node where the State Type is se to Number. There the Node is working.

**Comment by Wibias** [comment] 2020-03-30 23:52
So this node is working:

![image](https://user-images.githubusercontent.com/37517432/77972605-2d8ba500-72f2-11ea-99f2-665ed5a2fc24.png)

This node isn't working:

![image](https://user-images.githubusercontent.com/37517432/77972622-367c7680-72f2-11ea-8972-28de41fb2bc5.png)

**Comment by zachowj** [comment] 2020-03-31 01:03
I can't seem to reproduce this. Can you export the flow in the image and also add debug nodes with full the message output for the nodes that are showing `NaN` as the status and post that?

> ![image](https://user-images.githubusercontent.com/37517432/77971819-fddb9d80-72ef-11ea-9824-456ff4fd9933.png)

**Comment by Wibias** [comment] 2020-03-31 05:54
So here is the flow.

```
[{"id":"625d73c8.69c46c","type":"tab","label":"Flow 1","disabled":false,"info":""},{"id":"5203b003.e7c0f","type":"server-events","z":"625d73c8.69c46c","name":"","server":"14cc4f67.33b9e1","event_type":"","exposeToHomeAssistant":false,"haConfig":[{"property":"name","value":""},{"property":"icon","value":""}],"x":280,"y":160,"wires":[[]]},{"id":"7fede09f.e688e","type":"server-state-changed","z":"625d73c8.69c46c","name":"","server":"14cc4f67.33b9e1","version":1,"exposeToHomeAssistant":false,"haConfig":[{"property":"name","value":""},{"property":"icon","value":""}],"entityidfilter":"light.badezimmer_lampe_1","entityidfiltertype":"exact","outputinitially":false,"state_type":"str","haltifstate":"on","halt_if_type":"str","halt_if_compare":"is_not","outputs":2,"output_only_on_state_change":true,"x":380,"y":100,"wires":[["cac3d167.2ffed"],[]]},{"id":"77a3bc40.630a24","type":"poll-state","z":"625d73c8.69c46c","name":"","server":"14cc4f67.33b9e1","version":1,"exposeToHomeAssistant":false,"haConfig":[{"property":"name","value":""},{"property":"icon","value":""}],"updateinterval":"60","updateIntervalUnits":"seconds","outputinitially":false,"outputonchanged":true,"entity_id":"light.badezimmer_lampe_1","state_type":"str","halt_if":"","halt_if_type":"str","halt_if_compare":"is","outputs":1,"x":370,"y":40,"wires":[["8eb755d9.bb9a08"]]},{"id":"e7c6217b.1857c","type":"api-call-service","z":"625d73c8.69c46c","name":"","server":"14cc4f67.33b9e1","version":1,"debugenabled":false,"service_domain":"light","service":"turn_on","entityId":"light.badezimmer_lampe_1","data":"","dataType":"json","mergecontext":"","output_location":"","output_location_type":"none","mustacheAltTags":false,"x":310,"y":280,"wires":[[]]},{"id":"1bac1195.8c37ce","type":"api-current-state","z":"625d73c8.69c46c","name":"","server":"14cc4f67.33b9e1","version":1,"outputs":1,"halt_if":"","halt_if_type":"str","halt_if_compare":"is","override_topic":false,"entity_id":"light.badezimmer_lampe_1","state_type":"str","state_location":"payload","override_payload":"msg","entity_location":"data","override_data":"msg","blockInputOverrides":false,"x":380,"y":220,"wires":[["d7d45d1a.dc70f"]]},{"id":"61d677ef.561de8","type":"inject","z":"625d73c8.69c46c","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":120,"y":240,"wires":[["e7c6217b.1857c","1bac1195.8c37ce"]]},{"id":"cac3d167.2ffed","type":"debug","z":"625d73c8.69c46c","name":"","active":true,"tosidebar":true,"console":true,"tostatus":true,"complete":"payload","targetType":"msg","x":720,"y":100,"wires":[]},{"id":"d7d45d1a.dc70f","type":"debug","z":"625d73c8.69c46c","name":"","active":true,"tosidebar":true,"console":true,"tostatus":true,"complete":"payload","targetType":"msg","x":720,"y":220,"wires":[]},{"id":"8eb755d9.bb9a08","type":"debug","z":"625d73c8.69c46c","name":"","active":true,"tosidebar":true,"console":true,"tostatus":true,"complete":"payload","targetType":"msg","x":720,"y":40,"wires":[]},{"id":"b7e835fc.4da738","type":"server-state-changed","z":"625d73c8.69c46c","name":"Waschmaschine Leistung","server":"14cc4f67.33b9e1","version":1,"exposeToHomeAssistant":false,"haConfig":[{"property":"name","value":""},{"property":"icon","value":""}],"entityidfilter":"sensor.powr2_1_energy_power","entityidfiltertype":"substring","outputinitially":true,"state_type":"num","haltifstate":"2","halt_if_type":"num","halt_if_compare":"gte","outputs":2,"output_only_on_state_change":true,"x":330,"y":340,"wires":[[],["34bb5e5c.e15b62"]]},{"id":"34bb5e5c.e15b62","type":"debug","z":"625d73c8.69c46c","name":"","active":true,"tosidebar":true,"console":true,"tostatus":true,"complete":"payload","targetType":"msg","x":720,"y":340,"wires":[]},{"id":"14cc4f67.33b9e1","type":"server","z":"","name":"Home Assistant","legacy":false,"addon":false,"rejectUnauthorizedCerts":true,"ha_boolean":"y|yes|true|on|home|open","connectionDelay":true,"cacheJson":true}]
```

For this:

![image](https://user-images.githubusercontent.com/37517432/77991576-968c1080-7324-11ea-974e-4a390c4e03e7.png)

**Comment by jparthum** [comment] 2020-03-31 13:18
I'm having a similar issue that seems to be specific to having `Output on Connect` selected. These nodes are configured identically otherwise...

![](https://i.imgur.com/Ol87Rho.png)

Complete `msg` output:
```
{
   "topic":"input_boolean.dummy_switch",
   "payload":null,
   "data":{
       "entity_id":"input_boolean.dummy_switch",
       "old_state":{
           "entity_id":"input_boolean.dummy_switch",
           "state":null,
           "attributes":{
               "editable":false,
               "friendly_name":"Dummy Switch for testing",
               "icon":"mdi:format-superscript"
           },
           "last_changed":"2020-03-31T12:57:35.090677+00:00",
           "last_updated":"2020-03-31T12:57:35.090677+00:00",
           "context":{
               "id":"927b499e07164fddaab9e352ae2a5283",
               "parent_id":null,
               "user_id":"222a5c1842ee429ea527bd509fb366a0"
           },
           "timeSinceChangedMs":20953,
           "original_state":null
       },
       "new_state":{
           "entity_id":"input_boolean.dummy_switch",
           "state":null,
           "attributes":{
               "editable":false,
               "friendly_name":"Dummy Switch for testing",
               "icon":"mdi:format-superscript"
           },
           "last_changed":"2020-03-31T12:57:35.090677+00:00",
           "last_updated":"2020-03-31T12:57:35.090677+00:00",
           "context":{
               "id":"927b499e07164fddaab9e352ae2a5283",
               "parent_id":null,
               "user_id":"222a5c1842ee429ea527bd509fb366a0"
           },
           "timeSinceChangedMs":20953,
           "original_state":null
       }
   },
   "_msgid":"c5d6f09d.991b1"
}
```

---

Although it doesn't seem to apply to all Domains, in this case (`input_boolean`), changing the state of the entity clears the NaN error...

![](https://i.imgur.com/jJ6cjAP.png)

Complete `msg` output:
```
{
   "topic":"input_boolean.dummy_switch",
   "payload":"on",
   "data":{
       "entity_id":"input_boolean.dummy_switch",
       "old_state":{
           "entity_id":"input_boolean.dummy_switch",
           "state":"off",
           "attributes":{
               "editable":false,
               "friendly_name":"Dummy Switch for testing",
               "icon":"mdi:format-superscript"
           },
           "last_changed":"2020-03-31T12:58:59.051047+00:00",
           "last_updated":"2020-03-31T12:58:59.051047+00:00",
           "context":{
               "id":"4e2392240af34333906c18e3b5960526",
               "parent_id":null,
               "user_id":"222a5c1842ee429ea527bd509fb366a0"
           }
       },
       "new_state":{
           "entity_id":"input_boolean.dummy_switch",
           "state":"on",
           "attributes":{
               "editable":false,
               "friendly_name":"Dummy Switch for testing",
               "icon":"mdi:format-superscript"
           },
           "last_changed":"2020-03-31T12:59:00.126791+00:00",
           "last_updated":"2020-03-31T12:59:00.126791+00:00",
           "context":{
               "id":"8e8b056bae204a67ae54a390e33ada23",
               "parent_id":null,
               "user_id":"222a5c1842ee429ea527bd509fb366a0"
           },
           "timeSinceChangedMs":12
       }
   },
   "_msgid":"2cd1aa7b.a1c8e6"
}
```

**Comment by bikefright** [comment] 2020-03-31 16:13
Same problem here with <current state>, <poll state> & <trigger state> nodes with respect to string-based outputs giving me NaN.

I've noticed that if I create a new (identical Base URL and Access Token) server node for HA and then set any of my non-working [NaN] nodes to use the "new" HA server, I get the expected results - i.e. it is a fix for this problem for me.

Perhaps you could try this same fix to see if it also fixes it for you (i.e. get's rid of the Not A Number [NaN] erroneous outputs from string-based HA nodes)?

bikefright.

**Comment by bikefright** [comment] 2020-03-31 16:38
Sorry. Forget that.  Too hasty in posting. After a short time, the same nodes that had the problem revert from (for example) state "heat" or state "home" to "NaN" again.

So this was NOT a fix after all.
bikefright.

**Comment by Wibias** [comment] 2020-03-31 16:50
Yea same. Just tried that. Changing the Server fixed it for some minutes before switching back to NaN.

**Comment by bikefright** [comment] 2020-03-31 18:51
So....I've reverted to 0.20.2 and that does seem to have fixed things.  Been stable for an hour now.  All string-based output nodes working and triggering as they should.

FWIW: I am running the exact same node.js and node-red versions as you @Wibias.  I am running in a standalone docker on ubuntu 18.04.3 LTS if that makes a difference.  I also went through the same upgrade path as you that led me to find this problem.

For me, reverting was a simple as:
connecting to my docker container, entering the /data area and issuing the npm install specifying the 0.20.2 version as follows:
```
docker container exec -u 0 -it nodered bash
cd /data
npm install node-red-contrib-home-assistant-websocket@0.20.2
```
Then a quick restart of my nodered container via portainer.

I apprecaite the problem might not specifically start immediately after v0.20.2, but I have a fix and don't want the heating/hot-water/cameras etc. off tonight :-)

**If I can help troubleshoot this further for the owner, I'm more than willing to spinup a new node-red docker, attach it to my HA and roll backwards/forwards/gather logs etc.**

In my main node-red instance, everything now works to/from HA, which is what is important to me (and the wife!) So I'll leave that instance alone until the cause is isolated.

bikefright.

**Comment by zachowj** [comment] 2020-04-01 10:20
I still haven't been able to reproduce this on any of my test setups or my production machine. So it's been hard tracking it down. I have gone through all the things that have changed from 0.21.5 to 0.22.0 and nothing is standing out to me.

@bikefright or anyone that has a moment and the ability can you set through the dev version on npm and see if you can find where the bug was introduced? 

They can be installed via npm using the command line
```
npm node-red-contrib-home-assistant-websocket@0.21.6-dev.<git-hash>
``` 

My guess's somewhere between `0.21.6-dev.2ee957bee` and `0.21.6-dev.aca1558dc`

**Comment by matteos1** [comment] 2020-04-01 10:31
Is it possible to downgrade the HA websocket module within my node-red container installed from the add-on store? If so, how? 
same problem with NaN

**Comment by zachowj** [comment] 2020-04-01 10:42
@matteos1 I don't use the add-on but I believe it rebuilds the container when you restart it.

**Comment by matteos1** [comment] 2020-04-01 10:51
can I copy from old installation to new installation only the current-state directory?

**Comment by jelmerkk** [comment] 2020-04-01 10:56
Still happening in 0.22.1-dev.d07ff3565 @zachowj

**Comment by Wibias** [comment] 2020-04-01 11:02
I will try it when I get home.

**Comment by bikefright** [comment] 2020-04-01 12:33
@zachowj The plot thickens......bare install of node-red from nodered/node-red:latest with only this module (node-red-contrib-home-assistant-websocket)

I create a flow that contained 1 x inject, 3 x websocket nodes (poll, current state, state_change) and 3 x debug nodes and it works fine! I stepped through all dev versions and the problem simply doesn't occur!

So, I then exported ~14 websocket nodes from production into this test container  and stepped through from 0.21.6-dev.2ee957bee and **the NaN problem is back @node-red-contrib-home-assistant-websocket@0.21.6-dev.**11ddda1b0**** so you were spot on with your guess :-)

So it is both version _and_ more importantly (for me) the sheer number of nodes I have.

In production I have 342 nodes using this websocket module (there is a message there for me :-)!)

Let me know if you need me to do anything else (including supplying logs etc. or testing any potential fix).
bikefright.

**Comment by matteos1** [comment] 2020-04-02 19:34
Still no solution?

**Comment by zachowj** [comment] 2020-04-02 21:42
> So, I then exported ~14 websocket nodes from production into this test container and stepped through from 0.21.6-dev.2ee957bee and **the NaN problem is back @[node-red-contrib-home-assistant-websocket@0.21.6-dev](mailto:node-red-contrib-home-assistant-websocket@0.21.6-dev).**[11ddda1](https://github.com/zachowj/node-red-contrib-home-assistant-websocket/commit/11ddda1b065fdb597769bdf1b5f45cf23de02aa1)**** so you were spot on with your guess :-)

@bikefright Thanks for testing those. There were only two commits between those dev releases. One of them was removing an unused package and the other was updating some dependencies. I reverted the dependency updates. I still can't reproduce the NaN error on my end so this is just a shot in the dark.

This is the npm release with the reverted packages if someone with the error can try and see if it fixes the issue.

```
npm install node-red-contrib-home-assistant-websocket@0.22.1-fix226.0
```

**Comment by zaneclaes** [comment] 2020-04-02 21:52
I've fixed in on a fork. I'll push a PR momentarily @zachowj @matteos1

**Comment by zachowj** [comment] 2020-04-02 23:18
Thanks to @zaneclaes for finding the bug and fix.

Please test the below dev release and see if this fixes the issues. This should fix the issue for the events-state, poll-state, trigger-state, and current-state nodes.

```
npm install node-red-contrib-home-assistant-websocket@next
```

**Comment by bikefright** [comment] 2020-04-02 23:47
> npm install node-red-contrib-home-assistant-websocket@next

This hasn't fixed it for me on my test environment.  All four nodes still revert to NaN.  To be sure, I span up a brand new node-red:latest container, ran the above npm install and imported the same nodes for my previous tests from my prod instance.  This was to rule out any artefacts from my previous testing yesterday.

BTW, thanks for the effort thus far in trying to resolve this. Much appreciated.
bikefright.

**Comment by zachowj** [comment] 2020-04-03 00:00
@bikefright can you test `node-red-contrib-home-assistant-websocket@0.22.2-dev.5aa5b71e9` and see if that fixes the event: state node?

**Comment by bikefright** [comment] 2020-04-03 00:07
Ha! You beat me to it 🤓. I just saw that and was about to post: 0.22.2-dev.5aa5b71e9 fixes it for me.

To be clear, it fixes all four node types, not just the event:state.
bikefright.

**Comment by zachowj** [comment] 2020-04-03 00:25
@bikefright and hopefully for the last time please try `node-red-contrib-home-assistant-websocket@0.22.2-dev.10325fa7c`

**Comment by bikefright** [comment] 2020-04-03 00:37
@zachowj again, node-red-contrib-home-assistant-websocket@0.22.2-dev.10325fa7c works perfectly too.
![B496DA26-438A-42B5-B141-4B50549ABB11](https://user-images.githubusercontent.com/6887690/78312400-8d30bd00-754b-11ea-82e4-96f68456c11b.png)

**Closed** 2020-04-03 00:48 UTC

**Comment by knobunc** [comment] 2020-04-03 20:45
Ooh, thanks for working this out!
