### ISSUE TITLE
Cant uppdate past 0.59

### ISSUE THREAD

**Issue by hjalmarnilsson** [zachowj/node-red-contrib-home-assistant-websocket#1219] opened 2023-12-24 14:27 UTC
### Describe the bug

When trying to update from 0.59 it updates fine and new features are working. However the plugin disappears from node red as soon as the node red addon is restarted. (docker on hassio (running on pi)) .
All blocks are greyed out in the flow. I go in and install again.
It then claims it only installs 0.59 again.
I then upgrade to 0.62.2 and it upgrades, but as soon as it’s rebooted it’s gone again. 

### To Reproduce

1 upgrade from 0.59
2 reboot node red addon
3 now be-ha-ws isn’t installed all blocks with this plugin are greyed out.
4 works fine to install again. But disappears as soon as I restart node red

### Environment Information

Core
2023.12.3
Supervisor
2023.12.0
Operating System
11.2
Frontend
20231208.2

Hw pi 4.
Node red 16.0.2

**Comment by zachowj** [comment] 2023-12-24 15:44
Duplicate of #1206, #1214, #1217

**Closed by zachowj** 2023-12-24 15:44 UTC
